INSERT INTO IMPAY_SAMPLE (KEY, VALUE) VALUES ('001','aaaa');
INSERT INTO IMPAY_SAMPLE (KEY, VALUE) VALUES ('002','bbbb');
INSERT INTO IMPAY_SAMPLE (KEY, VALUE) VALUES ('003','cccc');
INSERT INTO IMPAY_SAMPLE (KEY, VALUE) VALUES ('004','dddd');
INSERT INTO IMPAY_SAMPLE (KEY, VALUE) VALUES ('005','eeee');
INSERT INTO IMPAY_SAMPLE (KEY, VALUE) VALUES ('006','ffff');


INSERT INTO USERS (username, password, enabled) VALUES ('user', 'password', true);
INSERT INTO AUTHORITIES (username, authority) VALUES ('user', 'ROLE_ADMIN');